name: Update IPFS Index

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch: 

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full commit history

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios dotenv

      - name: Fetch Pinned Files from Pinata
        run: node fetch_pins.js
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git fetch origin main
          
          # Reset to latest main branch to avoid conflicts
          git reset --hard origin/main

          # Ensure working directory is clean
          git clean -fd

          # Verify if there are any actual changes
          git add ipfs_index.json
          if git diff --cached --quiet; then
            echo "⚠️ No changes detected in ipfs_index.json. Skipping commit."
            exit 0
          fi

          git commit -m "Updated IPFS Index"
          git push origin main --force
