name: Update IPFS Index

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch: 

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full commit history

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios dotenv

      - name: Fetch Pinned Files from Pinata
        run: node fetch_pins.js
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          # Ensure the latest changes from GitHub are fetched
          git fetch origin main
          git reset --hard origin/main  # Reset to the latest version

          # Stage and commit changes
          git add ipfs_index.json
          git commit -m "Updated IPFS Index" || echo "No changes to commit"

          # Force push the updates to ensure synchronization
          git push origin main --force
