name: Update IPFS Index

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios dotenv

      - name: Fetch Pinned Files from Pinata
        run: node fetch_pins.js
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}

      - name: Debug Git Status Before Committing
        run: |
          echo "Checking Git status before committing..."
          git status
          ls -l ipfs_index.json
          cat ipfs_index.json

      - name: **Force Commit and Push Changes**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          
          echo "Fetching latest changes..."
          git fetch origin main

          echo "Ensuring clean working directory..."
          git reset --hard origin/main  # Ensures the latest commit is present
          git clean -fd  # Remove untracked files

          echo "Staging modified files..."
          git add ipfs_index.json  # Explicitly stage the modified JSON file
          
          echo "Checking status after adding..."
          git status

          echo "Committing changes..."
          git commit -m "Updated IPFS Index" || echo "No changes to commit"

          echo "Pushing changes..."
          git push origin main --force
