name: Update IPFS Index

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history to prevent push issues

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios dotenv

      - name: Fetch Pinned Files from Pinata
        run: node fetch_pins.js
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}

      - name: Debug Git Status
        run: |
          echo "Checking Git status before committing..."
          git status
          ls -l ipfs_index.json
          cat ipfs_index.json

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git fetch origin main
          git reset --hard origin/main  # Ensure we're on the latest commit
          git clean -fd  # Remove untracked files
          
          git add ipfs_index.json
          git commit -m "Updated IPFS Index" || echo "No changes to commit"
          git push origin main || (git pull --rebase && git push origin main)
