name: Update IPFS Index

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full commit history

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios dotenv

      - name: Fetch Pinned Files from Pinata
        run: node fetch_pins.js
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}

      - name: Ensure Git is in Sync
        run: |
          git fetch origin main
          git reset --hard origin/main  # Ensures the latest version of main
          git clean -fd  # Remove untracked files
          git status

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          
          echo "Staging changes..."
          git add ipfs_index.json
          
          echo "Checking status before committing..."
          git status
          
          echo "Committing changes..."
          git commit -m "Updated IPFS Index" || echo "No changes to commit"
          
          echo "Pushing changes..."
          git push origin main || echo "Push failed, retrying..." && git pull --rebase && git push origin main
